//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string STARTENGINE = "startengine";
        
        public const string STOPENGINE = "stopengine";
        
        public const string BARRELSLOADING = "barrelsloading";
        
        public const string PLANKSLOADING = "planksloading";
        
        public const string BOXESLOADING = "boxesloading";
        
        public const string COLLISION = "collision";
        
        public const string HIGHRPM = "highrpm";
        
        public const string GEARSHIFT = "gearshift";
    }
}
